---
title: "Exercise 1.3 Parameter setting and simulation"
author: "Nan-Hung Hsieh"
date: "2019/12/09 (update: `r Sys.Date()`)"
output: 
  html_document:
    toc: true
    toc_depth: 2
    number_sections: false
  fig_caption: yes  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd('..')
wd <- getwd()
knitr::opts_knit$set(root.dir =  wd)
```

```{R message=FALSE, warning=FALSE}
library(tidyverse)
library(httk)
library(simuloR)
theme_set(theme_bw())
```


## Exercise

- Extract the chemical information from httk package

```{r}
parms <- httk::parameterize_1comp(chem.name = "theophylline")
parms
```

- Use the parameters in the developed model and conduct the simulation 
- Compare the difference between data and the model simulation result (Cmax, Tmax)

## Simulation by R

R

```{r}
ffpk <- function(D, Fa, ka, ke, V, t){
    MW <- 180.167
    A <- (D * Fa * ka)/(V * (ka - ke))
    C <- A * exp(-ke * t) - A * exp(-ka * t)
    #C_uM <- C/MW*1000
    return(C)
}
```


```{r}
MW <- parms$MW
Fgutabs <- parms$Fgutabs * parms$hepatic.bioavailability
kgutabs <- parms$kgutabs
kelim <- parms$kelim
Vdist <- parms$Vdist
```


```{r}
dose1 <- subset(Theoph, Subject == 1) %>% summarise(dose = mean(Dose))
t1 <- subset(Theoph, Subject == 1) %>% select(Time)
out1 <- ffpk(D = dose1$dose, Fa = Fgutabs, ka = kgutabs, ke = kelim, V = Vdist, t=t1$Time)
out1
```


```{r}
conc1 <- subset(Theoph, Subject == 1) %>% select(conc)
plot(t1$Time, conc1$conc)
lines(t1$Time, out1)

```

```{r}
data.frame(t1, out1)
```


## Simulation by MCSim

```
Integrate (Lsodes, 1e-8, 1e-8, 1);

MW         = 180.167;  # moleculor mass (g/mol)
IngDose    = 4.02;     # ingested dose (mg)
Period     = 48;       # period of the exposure/no exposure cycle (h)
Fgutabs    = 0.9142;   # bioavailability (-) 
kgutabs    = 2.18;     # absortion rate (/h)
kelim      = 0.2654;   # elimination rate constant (/h)
Vdist      = 0.7802;   # volumes (L)

Simulation {
  Print (C_rest 0.00   0.25   0.57   1.12   2.02   3.82   5.10   7.03   9.05  12.12  24.37);
}
End.
```

```{r}
mcsim(model = "models/pbtk1cpt.model", input = "inputs/pbtk1cpt.in")
```


```{r}
read.delim("sim.out")
```

```{r}
read.delim("sim.out", skip = 1)
```


```{r}
out <- mcsim(model = "models/pbtk1cpt.model", input = "inputs/pbtk1cpt.in")
out
```

```{r}
plot(t1$Time, conc1$conc)
lines(out$Time, out$Conc)
```
